TransactionSystem/Models/Transaction.cs
public class Transaction
{
    public int Customer_id { get; set; }
    public int Product_id { get; set; }
    public int Quantity { get; set; }
    public DateTime Transaction_date { get; set; }
}

TransactionSystem/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace TransactionSystem.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

TransactionSystem/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Http;
using TransactionSystem.Controlers;

namespace TransactionSystem.Pages
{

    public class IndexModel : PageModel
    {
        [BindProperty]
        public User User { get; set; }

        
        public LoginController loginController = new LoginController();
        private string userEmail;
        private string userPassword;
        private string userName;


        public async Task<IActionResult> OnPostLogIn()
        {
            if(User.Email == null)
            {
                ModelState.AddModelError(string.Empty, "Wprowadz dane użytkownika.");
                return Page();
            }

            if(User.Email == "admin" && User.Password == "admin")
            {
                HttpContext.Session.SetString("Admin", "true");
                HttpContext.Session.SetString("Username", "admin");
                return RedirectToPage("./AdminPanel");
            }

            User LoginUser = await loginController.LogIn(User.Email);
            
            if (LoginUser == null)
            {
                ModelState.AddModelError(string.Empty, "Nie znaleziono użytkownika.");
                return Page();
            }
            else
            {
                User firstUser = LoginUser;
                userName = firstUser.Name;
                userEmail = firstUser.Email;
                userPassword = firstUser.Password;
            }

            if (User.Email == userEmail && User.Password == userPassword)
            {
                HttpContext.Session.SetString("Username", userName);
                return RedirectToPage("./Transactions");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Chuj.");
                return Page();
            }
        }
    }
}

TransactionSystem/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TransactionSystem.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

TransactionSystem/Pages/AddProduct.cshtml
@page
@model TransactionSystem.Pages.AddProductModel

<h2>Dodaj produkt</h2>

<form method="post" asp-page-handler="AddProduct">
    <label for="Name" class="form-label">Nazwa:</label>
    <input type="text" class="form-control" id="Name" asp-for="product.Name">

    <label for="Price" class="form-label">Cena:</label>
    <input type="text" class="form-control" id="Price" asp-for="product.Price">

    <br>
    <input class="btn btn-primary" type="submit" value="Dodaj Produkt">

</form>
<br>
<h2>Produkty</h2>

<table class="table table-striped-columns">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nazwa</th>
            <th>Cena</th>
            <th>Usuń</th>
            <th>Edytuj</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var products in Model.products)
        {
            <tr>
                <td>@products.Id</td>
                <td>@products.Name</td>
                <td>@products.Price</td>
                <td>
                    <form method="post" asp-page-handler="Delete">
                        <input type="hidden" name="Id" value="@products.Id" />
                        <button type="submit" class="btn btn-danger">X</button>
                    </form>
                </td>
                <td><button type="button" onclick="showEditRow(@products.Id)" class="btn btn-primary">Edit</button></td>
            </tr>

            <tr id="edit-row-@products.Id" class="edit-row" style="display: none">
                <td colspan="3">
                    <form method="post" asp-page-handler="EditProduct">
                        <div>
                            <label for="productWithIDs.Name" class="control-label">Nazwa:</label>
                            <input asp-for="productWithIDs.Name" class="form-control" />
                        </div>
                        <div>
                            <label for="productWithIDs.Price" class="control-label">Cena:</label>
                            <input asp-for="productWithIDs.Price" class="form-control" />
                        </div>
                        <br>
                        <div>
                            <button class="btn btn-success" type="submit">Zapisz</button>
                        </div>
                        <div>
                            <input type="hidden" asp-for="productWithIDs.Id" value="@products.Id" />
                        </div>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>





@section Scripts {
    <script>
        function showEditRow(id) {
            var $editRow = $("#edit-row-" + id);

            if ($editRow.is(":visible")) {
                $editRow.hide();
            }
            else {
                // Ukryj wszystkie wiersze edycji
                $(".edit-row").hide();

                // Pokaż wybrany wiersz edycji
                $editRow.show();
            }
        }

    </script>
}

TransactionSystem/Pages/AddUser.cshtml
@page
@model TransactionSystem.Pages.Admin.AddUserModel
<head>
    <link rel="stylesheet" href="~/css/style.css" />

</head>
<h2>Dodaj użytkownika</h2>


<form method="post" asp-page-handler="AddCustomer">
    <label for="Name" class="form-label">Imię:</label>
    <input type="text" class="form-control" id="Name" asp-for="customer.Name">

    <label for="Email" class="form-label">Email:</label>
    <input type="text" class="form-control" id="Email" asp-for="customer.Email">

    <label for="Phone" class="form-label">Telefon:</label>
    <input type="text" class="form-control" id="Phone" asp-for="customer.Phone">

    <label for="Password" class="form-label">Hasło:</label>
    <input type="password" class="form-control" id="Password" asp-for="customer.Password">

    <Br>
    <input class="btn btn-primary" type="submit" value="Dodaj Użytkownika">

</form>
<br>
<h2>Użytkownicy</h2>


<table class="table table-striped-columns">
    <thead>
        <tr>
            <th>Id</th>
            <th>Imie</th>
            <th>Telefon</th>
            <th>Email</th>
            <th>Hasło</th>
            <th>Usuń</th>
            <th>Edytuj</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model.users)
        {
            <tr>
                <td>@user.Id</td>
                <td>@user.Name</td>
                <td>@user.Phone</td>
                <td>@user.Email</td>
                <td>@user.Password</td>
                <td>
                    <form method ="post" asp-page-handler="Delete">
                        <input type="hidden" name="Id" value="@user.Id" />
                        <button type="submit" class="btn btn-danger">X</button>
                    </form>
                </td>
                <td><button type="button" onclick="showEditRow(@user.Id)" class="btn btn-primary">Edit</button></td>
            </tr>

            <tr id="edit-row-@user.Id" class="edit-row" style="display: none">
                <td colspan="3">
                    <form method="post" asp-page-handler="EditUser">
                        <div>
                            <label for="user.Name" class="control-label">Imię:</label>
                            <input asp-for="user.Name" class="form-control" />
                        </div>
                        <div>
                            <label for="user.Phone" class="control-label">Telefon:</label>
                            <input asp-for="user.Phone" class="form-control" />
                        </div>
                        <div>
                            <label for="user.Email" class="control-label">Email:</label>
                            <input asp-for="user.Email" class="form-control" />
                        </div>
                        <div>
                            <label for="user.Password" class="control-label">Hasło:</label>
                            <input asp-for="user.Password" class="form-control" />
                        </div>
                        <br>
                        <div>
                            <button class="btn btn-success" type="submit">Zapisz</button>
                        </div>
                        <div>
                            <input type="hidden" asp-for="user.Id" value="@user.Id" />
                        </div>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>


@section Scripts {
    <script>
        function showEditRow(id) {
            var $editRow = $("#edit-row-" + id);

            if ($editRow.is(":visible")) {
                $editRow.hide();
            }
            else {
                // Ukryj wszystkie wiersze edycji
                $(".edit-row").hide();

                // Pokaż wybrany wiersz edycji
                $editRow.show();
            }
        }

    </script>
}

TransactionSystem/Pages/AdminPanel.cshtml
@page
@model AdminPanelModel

<h1>Panel administratora</h1>

<ul>
    <li><a href="/AddUser"><i class="fas fa-user-plus"></i>Użytkownicy</a></li>
    <li><a href="/AddProduct"><i class="fas fa-plus-circle"></i>Produkty</a></li>
    <li><a href="/Transactions"><i class="fas fa-receipt"></i>Transakcje</a></li>
</ul>

TransactionSystem/Pages/Index.cshtml
@page
@model TransactionSystem.Pages.IndexModel
@{
    ViewData["Title"] = "Logowanie";
}

<h1>Logowanie</h1>

<form method="post">
    <div>
        <label for="Username">Email:</label>
        <input asp-for="User.Email" />
    </div>
    <div>
        <label for="Password">Hasło:</label>
        <input asp-for="User.Password" type="password" />
    </div>
    <div>
        <button type="submit" asp-page-handler="LogIn">Zaloguj</button>
    </div>
</form>

<br>
<br>
<br>

<h5>Reszta Screenów Tutaj</h5>
<video width="800" height="600" controls>
    <source src="/Videos/Video.mp4" type="video/mp4">
    Twoja przeglądarka nie obsługuje odtwarzania plików wideo.
</video>

@section Scripts {
    <script>
        @if (!ViewData.ModelState.IsValid)
        {
            // Jeśli ModelState zawiera błędy, wywołaj funkcję do wyświetlenia popupa
            <text>
                $(document).ready(function () {
                    showErrorPopup(htmlDecode("@ViewData.ModelState[""].Errors[0].ErrorMessage"));
                });

            function htmlDecode(input) {
                var doc = new DOMParser().parseFromString(input, "text/html");
                return doc.documentElement.textContent;
            }

            function showErrorPopup(errorMessage) {
                Swal.fire({
                    icon: 'error',
                    title: 'Error',
                    html: errorMessage,
                    confirmButtonText: 'OK'
                });
            }
            </text>
        }
    </script>
}

TransactionSystem/Pages/Transactions.cshtml
@page
@model TransactionSystem.Pages.TransactionsModel
@{
    ViewData["Title"] = "Transakcje";
}
<head>
    <link rel="stylesheet" href="~/css/style.css" />

</head>



<h1>Witaj, @Model.Username!</h1>

<h2>Dodaj nową transakcję</h2>

<form method="post" asp-page-handler="AddTransaction">
<div class="form-group">
    <label class="control-label">Produkt:</label>
    <select asp-for="transactions.Product_id" class="form-control">
        <option value="">-- Wybierz --</option>
        @foreach (var obj in Model.products)
        {
            <option value="@obj.Id">@obj.Name</option>
        }
    </select>
</div>
<div class="form-group">
    <label class="control-label">Klient:</label>
    <select asp-for="transactions.Customer_id" class="form-control">
        <option value="">-- Wybierz --</option>
        @foreach (var obj in Model.users)
        {
            <option value="@obj.Id">@obj.Name</option>
        }
    </select>
</div>
    <div>
        <label for="transactions.Quantity" class="control-label">Ilość:</label>
        <input asp-for="transactions.Quantity" class="form-control"/>
    </div>
    <div>
    @{
        DateTime currentTimeUtc = DateTime.UtcNow;
        DateTime currentTimeWithOffset = currentTimeUtc.AddHours(2);
        string currentTimeWithOffsetString = currentTimeWithOffset.ToString("yyyy-MM-ddTHH:mm:ssZ");
    }
    <input type="hidden" asp-for="transactions.Transaction_date" value="@currentTimeWithOffsetString" />
    </div>
<br>
    <div>
    <input class="btn btn-primary" type="submit" value="Dodaj Transakcje">
    </div>
</form>
<br>
<h2>Lista produktów</h2>





<table class="table table-striped-columns">
    <thead>
        <tr>
            <th>Id</th>
            <th>Klient</th>
            <th>Produkt</th>
            <th>Data</th>
            <th>Ilość</th>
            <th>Usuń</th>
            <th>Edytuj</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var transaction in Model.transactionExtra)
        {
            <tr>
                <td>@transaction.Id</td>
                <td>@transaction.Customer_name</td>
                <td>@transaction.Product_name</td>
                <td>@transaction.Transaction_date</td>
                <td>@transaction.Quantity</td>
                <td>
                    <form method ="post" asp-page-handler="DeleteTransaction">
                        <input type="hidden" name="Id" value="@transaction.Id" />
                        <button type="submit" class="btn btn-danger">X</button>
                    </form>
               </td>
                <td>
                    <button class="btn btn-primary" onclick="showEditRow(@transaction.Id)">Edit</button>
                </td>
            </tr>

            <tr id="edit-row-@transaction.Id" class="edit-row" style="display: none">
                <td colspan="3">
                    <form method="post" asp-page-handler="EditTransaction">
                        <div class="form-group">
                            <label class="control-label">Produkt:</label>
                            <select asp-for="transactionsWithIDs.Product_id" class="form-control">
                                <option value="">-- Wybierz --</option>
                                @foreach (var obj in Model.products)
                                {
                                    <option value="@obj.Id">@obj.Name</option>
                                }
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Klient:</label>
                            <select asp-for="transactionsWithIDs.Customer_id" class="form-control">
                                <option value="">-- Wybierz --</option>
                                @foreach (var obj in Model.users)
                                {
                                    <option value="@obj.Id">@obj.Name</option>
                                }
                            </select>
                        </div>
                        <div>
                            <label for="transactions.Quantity" class="control-label">Ilość:</label>
                            <input asp-for="transactionsWithIDs.Quantity" class="form-control" />
                        </div>
                        <br>
                        <div>
                            <button class="btn btn-success" type="submit">Zapisz</button>
                        </div>
                        <div>
                            @{
                                DateTime currentTimeEdit = DateTime.UtcNow;
                                DateTime currentTimeWithOffsetEdit = currentTimeEdit.AddHours(2);
                                string currentTimeWithOffsetStringEdit = currentTimeWithOffsetEdit.ToString("yyyy-MM-ddTHH:mm:ssZ");
                            }
                            <input type="hidden" asp-for="transactionsWithIDs.Transaction_date" value="@currentTimeWithOffsetStringEdit" />
                        </div>
                        <div>

                            <input type="hidden" asp-for="transactionsWithIDs.Id" value="@transaction.Id" />
                        </div>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>




@section Scripts {
    <script>
        function showEditRow(id) 
        {
            var $editRow = $("#edit-row-" + id);

            if ($editRow.is(":visible")) {
                $editRow.hide();
            } 
            else 
            {
                // Ukryj wszystkie wiersze edycji
                $(".edit-row").hide();

                // Pokaż wybrany wiersz edycji
                $editRow.show();
            }
        }

    </script>
}